"""add book field

Revision ID: 4f963d947616
Revises: 67710b44a467
Create Date: 2018-03-16 08:08:05.610351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f963d947616'
down_revision = '67710b44a467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('avg', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'avg')
    # ### end Alembic commands ###
